# -*- ruby -*-

# DO NOT EDIT THIS FILE. Instead, edit Rakefile, and run `rake bundler:gemfile`.

source "https://rubygems.org/"


gem "minitest", "~>5.10", :group => [:development, :test]
gem "rdoc", "~>4.0", :group => [:development, :test]
gem "rake-compiler", "~>1.0", :group => [:development, :test]
gem "hoe", "~>3.16", :group => [:development, :test]

# vim: syntax=ruby
